from tkinter import BOTH, BOTTOM, CENTER, END, HORIZONTAL, NONE, RAISED, RIGHT, X, Y
from typing import Literal


class Styles:
    WHITE_COLOR = "#FFFFFF"
    BLACK_COLOR = "#000000"
    RED_COLOR = "#FF0000"
    GREEN_COLOR = "#00FF00"

    FONT_TIMES = "Times"
    FONT_TIMES_10 = f"{FONT_TIMES} 10"
    FONT_TIMES_12 = f"{FONT_TIMES} 12"
    FONT_TIMES_13 = f"{FONT_TIMES} 13"
    FONT_TIMES_14 = f"{FONT_TIMES} 14"
    FONT_TIMES_15 = f"{FONT_TIMES} 15"
    FONT_TIMES_20 = f"{FONT_TIMES} 20"

    WRAP_NONE = NONE

    FILL_BOTH = BOTH
    FILL_Y = Y
    FILL_X = X

    SIDE_RIGHT = RIGHT
    SIDE_BOTTOM = BOTTOM

    ORIENT_HORIZONTAL = HORIZONTAL

    POSITION_END = END

    ANCHOR_CENTER = CENTER

    RELIEF_RAISED: Literal["raised"] = RAISED
